stages:
  - build
  - deploy

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run lint
    - npm test
  artifacts:
    paths:
      - node_modules/

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t node-test .
    - docker tag node-test:18 192.168.2.41/node-test:latest
    - docker push 192.168.2.41/node-test:latest